import  com.makefriend.makefriend.model.Report;

rule "More than 5 reports in 3 hours to one user"
    when
        $t1: Report($cUsername: username)
        Number(intValue >= 4) from accumulate(
            $t2: Report(
                this != $t1,
                username == $cUsername,
                this meets[24h] $t1
            ),
            count($t2)
        )
    then
        $t1.setBan(true);
end
