import com.makefriend.makefriend.model.MessageSuggest
import com.makefriend.makefriend.model.MessageFromRule

rule "A and B like football"
agenda-group "Message"
lock-on-active true
    when
        $ms: MessageSuggest(getUserAInterests() contains "Football" && getUserBInterests() contains "Football")
    then
        MessageFromRule messageFromRule = new MessageFromRule("What is your favourite football team?",2);
        $ms.getMessageSuggests().add(messageFromRule);
end

rule "A and B like Volleyball"
agenda-group "Message"
lock-on-active true
    when
        $ms: MessageSuggest(getUserAInterests() contains "Football" && getUserBInterests() contains "Football")
    then
        MessageFromRule messageFromRule = new MessageFromRule("What is your favourite volleyball team?",2);
        $ms.getMessageSuggests().add(messageFromRule);
end

rule "A and B like Basketball"
agenda-group "Message"
lock-on-active true
    when
        $ms: MessageSuggest(getUserAInterests() contains "Basketball" && getUserBInterests() contains "Basketball")
    then
        MessageFromRule messageFromRule = new MessageFromRule("What is your favourite basketball team?",2);
        $ms.getMessageSuggests().add(messageFromRule);
end

rule "A like sport"
agenda-group "Message"
lock-on-active true
    when
        $ms: MessageSuggest(userAInterests contains "Football" || userAInterests contains "Basketball" || userAInterests contains "Volleyball")
    then
        $ms.getCategoriesALiked().add("SPORT");
        update($ms);
end

rule "B like sport"
agenda-group "Message"
lock-on-active true
    when
        $ms:MessageSuggest(userBInterests contains "Football" || userBInterests contains "Basketball" || userBInterests contains "Volleyball")
    then
        $ms.getCategoriesBLiked().add("SPORT");
        update($ms);
end

rule "A and B like Sport"
agenda-group "Message"
    when
        $ms:MessageSuggest(!(getCommonCategories() contains "SPORT") && getCategoriesALiked() contains "SPORT" && getCategoriesBLiked() contains "SPORT")
    then
        MessageFromRule messageFromRule = new MessageFromRule("What is your favourite sport?",1);
        $ms.getMessageSuggests().add(messageFromRule);
        $ms.getCommonCategories().add("SPORT");
        update($ms);
end

rule "A like books"
agenda-group "Message"
lock-on-active true
    when
        $ms:MessageSuggest(getUserAInterests() contains "FantasyBooks" || getUserAInterests() contains "DramaBooks" || getUserAInterests() contains "PoetryBooks" || getUserAInterests() contains "DetectiveBooks" || getUserAInterests() contains "HistoryBooks")
    then
        $ms.getCategoriesALiked().add("BOOKS");
        update($ms);
end

rule "B like books"
agenda-group "Message"
lock-on-active true
    when
        $ms:MessageSuggest(getUserBInterests() contains "FantasyBooks" || getUserBInterests() contains "DramaBooks" || getUserBInterests() contains "PoetryBooks" || getUserBInterests() contains "DetectiveBooks" || getUserBInterests() contains "HistoryBooks")
    then
        $ms.getCategoriesBLiked().add("BOOKS");
        update($ms);
end

rule "A and B like Books"
agenda-group "Message"
    when
        $ms: MessageSuggest(!(getCommonCategories() contains "BOOKS") && getCategoriesALiked() contains "BOOKS" && getCategoriesBLiked() contains "BOOKS")
    then
        MessageFromRule messageFromRule = new MessageFromRule("What is your favourite book?",1);
        $ms.getMessageSuggests().add(messageFromRule);
        $ms.getCommonCategories().add("BOOKS");
        update($ms);
end

rule "A like tv and movies"
agenda-group "Message"
lock-on-active true
    when
        $ms: MessageSuggest(userBInterests contains "TV Shows" || userBInterests contains "Movies")
    then
        $ms.getCategoriesALiked().add("TVMOVIE");
        update($ms);
end

rule "B like tv and movies"
agenda-group "Message"
lock-on-active true
    when
        $ms: MessageSuggest(userBInterests contains "TV Shows" || userBInterests contains "Movies")
    then
        $ms.getCategoriesBLiked().add("TVMOVIE");;
        update($ms);
end

rule "A and B like tv"
agenda-group "Message"
    when
        $ms: MessageSuggest(!(getCommonCategories() contains "BOOKS") && getCategoriesALiked()contains "TVMOVIE" && getCategoriesBLiked() contains "TVMOVIE")
    then
        MessageFromRule messageFromRule = new MessageFromRule("What is your favourite thing on tv?",1);
        $ms.getMessageSuggests().add(messageFromRule);
        $ms.getCommonCategories().add("TVMOVIE");
        update($ms);
end

rule "A like Movies and B like Books"
agenda-group "Message"
    when
        $ms:MessageSuggest(getCategoriesALiked() contains "BOOKS" && getCategoriesBLiked() contains "Movies")
    then
        MessageFromRule messageFromRule = new MessageFromRule("What is your favourite book that is done after movie",3);
        $ms.getMessageSuggests().add(messageFromRule);
end

rule "B like Movies and A like Books"
agenda-group "Message"
    when
        $ms:MessageSuggest(getCategoriesALiked() contains "BOOKS" && getUserBInterests() contains "Movies")
    then
        MessageFromRule messageFromRule = new MessageFromRule("What is your favourite movie that is done after book",3);
        $ms.getMessageSuggests().add(messageFromRule);
end

rule "A likes music"
agenda-group "Message"
lock-on-active true
    when
        $ms:MessageSuggest(getUserAInterests() contains "Hip-hop" || getUserAInterests() contains "Rock" || getUserAInterests() contains "Metal" || getUserAInterests() contains "Pop")
    then
        $ms.getCategoriesALiked().add("MUSIC");
        update($ms);
end

rule "B likes music"
agenda-group "Message"
lock-on-active true
    when
        $ms:MessageSuggest(getUserBInterests() contains "Hip-hop" || getUserBInterests() contains "Rock" || getUserBInterests() contains "Metal" || getUserBInterests() contains "Pop")
    then
        $ms.getCategoriesBLiked().add("MUSIC");
        update($ms);
end

rule "A likes music and B likes music"
agenda-group "Message"
    when
        $ms:MessageSuggest(!(getCommonCategories() contains "MUSIC") && getCategoriesALiked() contains "MUSIC" && getCategoriesBLiked() contains "MUSIC")
    then
        MessageFromRule messageFromRule = new MessageFromRule("What is your favourite song?",1);
        $ms.getMessageSuggests().add(messageFromRule);
        $ms.getCommonCategories().add("MUSIC");
        update($ms);
end

rule "Both like music and both like tv"
agenda-group "Message"
    when
        $ms:MessageSuggest(getCommonCategories() contains "MUSIC" && getCommonCategories() contains "TVMOVIE")
    then
        MessageFromRule messageFromRule = new MessageFromRule("What is your favourite song from a tv show or movie?",3);
        $ms.getMessageSuggests().add(messageFromRule);
end


