import com.makefriend.makefriend.model.MessageSuggest
import com.makefriend.makefriend.model.MessageFromRule
import com.makefriend.makefriend.model.Interest
import com.makefriend.makefriend.model.User
import com.makefriend.makefriend.dto.UserListDTO
rule "A and B like football"
agenda-group "Message"
salience(10)
lock-on-active true
    when
        $ms: MessageSuggest(getUserAInterests() contains "Football" && getUserBInterests() contains "Football")
    then
        MessageFromRule messageFromRule = new MessageFromRule("What is your favourite football team?",2);
        $ms.getMessageSuggests().add(messageFromRule);
        System.out.println("Message: Both users like football");
end

rule "A and B like Volleyball"
agenda-group "Message"
salience(10)
lock-on-active true
    when
        $ms: MessageSuggest(getUserAInterests() contains "Football" && getUserBInterests() contains "Football")
    then
        MessageFromRule messageFromRule = new MessageFromRule("What is your favourite volleyball team?",2);
        $ms.getMessageSuggests().add(messageFromRule);
        System.out.println("Message: Both users like volleyball");

end

rule "A and B like Basketball"
agenda-group "Message"
salience(10)
lock-on-active true
    when
        $ms: MessageSuggest(getUserAInterests() contains "Basketball" && getUserBInterests() contains "Basketball")
    then
        MessageFromRule messageFromRule = new MessageFromRule("What is your favourite basketball team?",2);
        $ms.getMessageSuggests().add(messageFromRule);
        System.out.println("Message: Both users like basketball");
end

rule "A like sport"
agenda-group "Message"
salience(9)
lock-on-active true
    when
        $ms: MessageSuggest(userAInterests contains "Football" || userAInterests contains "Basketball" || userAInterests contains "Volleyball")
    then
        $ms.getCategoriesALiked().add("SPORT");
        System.out.println("User A likes sport");
        update($ms);
end

rule "B like sport"
agenda-group "Message"
salience(9)
lock-on-active true
    when
        $ms:MessageSuggest(userBInterests contains "Football" || userBInterests contains "Basketball" || userBInterests contains "Volleyball")
    then
        $ms.getCategoriesBLiked().add("SPORT");
        System.out.println("User B likes sport");
        update($ms);
end

rule "A and B like Sport"
agenda-group "Message"
salience(8)
    when
        $ms:MessageSuggest(!(getCommonCategories() contains "SPORT") && getCategoriesALiked() contains "SPORT" && getCategoriesBLiked() contains "SPORT")
    then
        MessageFromRule messageFromRule = new MessageFromRule("What is your favourite sport?",1);
        $ms.getMessageSuggests().add(messageFromRule);
        $ms.getCommonCategories().add("SPORT");
        System.out.println("Message: Both users like sport");
        update($ms);
end

rule "A like books"
agenda-group "Message"
salience(9)
lock-on-active true
    when
        $ms:MessageSuggest(getUserAInterests() contains "FantasyBooks" || getUserAInterests() contains "DramaBooks" || getUserAInterests() contains "PoetryBooks" || getUserAInterests() contains "DetectiveBooks" || getUserAInterests() contains "HistoryBooks")
    then
        $ms.getCategoriesALiked().add("BOOKS");
        System.out.println("User A likes books");
        update($ms);
end

rule "B like books"
agenda-group "Message"
salience(9)
lock-on-active true
    when
        $ms:MessageSuggest(getUserBInterests() contains "FantasyBooks" || getUserBInterests() contains "DramaBooks" || getUserBInterests() contains "PoetryBooks" || getUserBInterests() contains "DetectiveBooks" || getUserBInterests() contains "HistoryBooks")
    then
        $ms.getCategoriesBLiked().add("BOOKS");
        System.out.println("User B likes books");
        update($ms);
end

rule "A and B like Books"
salience(8)
agenda-group "Message"
    when
        $ms: MessageSuggest(!(getCommonCategories() contains "BOOKS") && getCategoriesALiked() contains "BOOKS" && getCategoriesBLiked() contains "BOOKS")
    then
        MessageFromRule messageFromRule = new MessageFromRule("What is your favourite book?",1);
        $ms.getMessageSuggests().add(messageFromRule);
        $ms.getCommonCategories().add("BOOKS");
        System.out.println("Message: Both users like books");
        update($ms);
end

rule "A like tv and movies"
agenda-group "Message"
salience(9)
lock-on-active true
    when
        $ms: MessageSuggest(userBInterests contains "TV Shows" || userBInterests contains "Movies")
    then
        $ms.getCategoriesALiked().add("TVMOVIE");
        System.out.println("User A likes tv and movies");
        update($ms);
end

rule "B like tv and movies"
salience(9)
agenda-group "Message"
lock-on-active true
    when
        $ms: MessageSuggest(userBInterests contains "TV Shows" || userBInterests contains "Movies")
    then
        $ms.getCategoriesBLiked().add("TVMOVIE");
        System.out.println("User B likes tv and movies");
        update($ms);
end

rule "A and B like tv"
salience(8)
agenda-group "Message"
    when
        $ms: MessageSuggest(!(getCommonCategories() contains "BOOKS") && getCategoriesALiked()contains "TVMOVIE" && getCategoriesBLiked() contains "TVMOVIE")
    then
        MessageFromRule messageFromRule = new MessageFromRule("What is your favourite thing on tv?",1);
        $ms.getMessageSuggests().add(messageFromRule);
        $ms.getCommonCategories().add("TVMOVIE");
        System.out.println("Message: Both users like tv and movies");
        update($ms);
end

rule "A like Movies and B like Books"
salience(7)
agenda-group "Message"
    when
        $ms:MessageSuggest(getCategoriesALiked() contains "BOOKS" && getCategoriesBLiked() contains "Movies")
    then
        MessageFromRule messageFromRule = new MessageFromRule("What is your favourite book that is done after movie",3);
        $ms.getMessageSuggests().add(messageFromRule);
        System.out.println("User A likes Movies and User B likes books");
end

rule "B like Movies and A like Books"
salience(7)
agenda-group "Message"
    when
        $ms:MessageSuggest(getCategoriesALiked() contains "BOOKS" && getUserBInterests() contains "Movies")
    then
        MessageFromRule messageFromRule = new MessageFromRule("What is your favourite movie that is done after book",3);
        $ms.getMessageSuggests().add(messageFromRule);
        System.out.println("User B likes Movies and User A likes books");
end

rule "A likes music"
salience(9)
agenda-group "Message"
lock-on-active true
    when
        $ms:MessageSuggest(getUserAInterests() contains "Hip-hop" || getUserAInterests() contains "Rock" || getUserAInterests() contains "Metal" || getUserAInterests() contains "Pop")
    then
        $ms.getCategoriesALiked().add("MUSIC");
        System.out.println("User A likes Music");
        update($ms);
end

rule "B likes music"
salience(9)
agenda-group "Message"
lock-on-active true
    when
        $ms:MessageSuggest(getUserBInterests() contains "Hip-hop" || getUserBInterests() contains "Rock" || getUserBInterests() contains "Metal" || getUserBInterests() contains "Pop")
    then
        $ms.getCategoriesBLiked().add("MUSIC");
        System.out.println("User B likes music");
        update($ms);
end

rule "A likes music and B likes music"
salience(8)
agenda-group "Message"
    when
        $ms:MessageSuggest(!(getCommonCategories() contains "MUSIC") && getCategoriesALiked() contains "MUSIC" && getCategoriesBLiked() contains "MUSIC")
    then
        MessageFromRule messageFromRule = new MessageFromRule("What is your favourite song?",1);
        $ms.getMessageSuggests().add(messageFromRule);
        $ms.getCommonCategories().add("MUSIC");
        System.out.println("Message: Both users like music");
        update($ms);
end

rule "Both like music and both like tv"
salience(6)
agenda-group "Message"
    when
        $ms:MessageSuggest(getCommonCategories() contains "MUSIC" && getCommonCategories() contains "TVMOVIE")
    then
        MessageFromRule messageFromRule = new MessageFromRule("What is your favourite song from a tv show or movie?",3);
        $ms.getMessageSuggests().add(messageFromRule);
        System.out.println("Message: Both users like music and both like tv");
end

rule "Select special message"
salience(-1)
agenda-group "Message"
    when
        $ms:MessageSuggest($messages: messageSuggests)
        Number(intValue >= 6) from accumulate(
            MessageFromRule($t: this, strength >= 2)
        from $messages,
        count($t)
        )
    then
    MessageFromRule messageFromRule = new MessageFromRule("We are the same",10);
    $ms.getMessageSuggests().add(messageFromRule);
    System.out.println("Special message");
end
